from typing import Any
from uvicorn.supervisors.basereload import BaseReload as BaseReload

logger: Any

class StatReload(BaseReload):
    reloader_name: str = ...
    mtimes: Any = ...
    def __init__(self, config: Any, target: Any, sockets: Any) -> None: ...
    def should_restart(self): ...
    def iter_py_files(self) -> None: ...
