from typing import Any

class HTMLResponse:
    content: Any = ...
    status_code: Any = ...
    def __init__(self, content: Any, status_code: Any) -> None: ...
    async def __call__(self, scope: Any, recieve: Any, send: Any) -> None: ...

class PlainTextResponse:
    content: Any = ...
    status_code: Any = ...
    def __init__(self, content: Any, status_code: Any) -> None: ...
    async def __call__(self, scope: Any, recieve: Any, send: Any) -> None: ...

def get_accept_header(scope: Any): ...

class DebugMiddleware:
    app: Any = ...
    def __init__(self, app: Any) -> None: ...
    async def __call__(self, scope: Any, receive: Any, send: Any): ...
