from typing import Any

PLACEHOLDER_FORMAT: Any
TRACE_LOG_LEVEL: int

def message_with_placeholders(message: Any): ...

class MessageLoggerMiddleware:
    task_counter: int = ...
    app: Any = ...
    logger: Any = ...
    def __init__(self, app: Any) -> None: ...
    async def __call__(self, scope: Any, receive: Any, send: Any): ...
