from typing import Any

class ProxyHeadersMiddleware:
    app: Any = ...
    trusted_hosts: Any = ...
    always_trust: Any = ...
    def __init__(self, app: Any, trusted_hosts: str = ...) -> None: ...
    async def __call__(self, scope: Any, receive: Any, send: Any): ...
