from typing import Any, Optional

def build_environ(scope: Any, message: Any, body: Any): ...

class WSGIMiddleware:
    app: Any = ...
    executor: Any = ...
    def __init__(self, app: Any, workers: int = ...) -> None: ...
    async def __call__(self, scope: Any, receive: Any, send: Any) -> None: ...

class WSGIResponder:
    app: Any = ...
    executor: Any = ...
    scope: Any = ...
    status: Any = ...
    response_headers: Any = ...
    send_event: Any = ...
    send_queue: Any = ...
    loop: Any = ...
    response_started: bool = ...
    exc_info: Any = ...
    def __init__(self, app: Any, executor: Any, scope: Any) -> None: ...
    async def __call__(self, receive: Any, send: Any) -> None: ...
    async def sender(self, send: Any) -> None: ...
    def start_response(self, status: Any, response_headers: Any, exc_info: Optional[Any] = ...) -> None: ...
    def wsgi(self, environ: Any, start_response: Any) -> None: ...
