from typing import Any
from uvicorn.subprocess import get_subprocess as get_subprocess

HANDLED_SIGNALS: Any
logger: Any

class BaseReload:
    config: Any = ...
    target: Any = ...
    sockets: Any = ...
    should_exit: Any = ...
    pid: Any = ...
    reloader_name: Any = ...
    def __init__(self, config: Any, target: Any, sockets: Any) -> None: ...
    def signal_handler(self, sig: Any, frame: Any) -> None: ...
    def run(self) -> None: ...
    process: Any = ...
    def startup(self) -> None: ...
    mtimes: Any = ...
    def restart(self) -> None: ...
    def shutdown(self) -> None: ...
    def should_restart(self) -> None: ...
