from typing import Any
from uvicorn import Config as Config
from uvicorn._types import LifespanReceiveMessage as LifespanReceiveMessage, LifespanScope as LifespanScope, LifespanSendMessage as LifespanSendMessage

STATE_TRANSITION_ERROR: str

class LifespanOn:
    config: Any = ...
    logger: Any = ...
    startup_event: Any = ...
    shutdown_event: Any = ...
    receive_queue: Any = ...
    error_occured: bool = ...
    startup_failed: bool = ...
    should_exit: bool = ...
    def __init__(self, config: Config) -> None: ...
    async def startup(self) -> None: ...
    async def shutdown(self) -> None: ...
    asgi: Any = ...
    async def main(self) -> None: ...
    async def send(self, message: LifespanSendMessage) -> None: ...
    async def receive(self) -> LifespanReceiveMessage: ...
